{% set name = "ilpy" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec762291186ea92b2b6c5650fe9ad3f61492d832d67d591162a68575e23cbc80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - ilpy
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/funkelab/ilpy
  summary: 'Unified API for ILP solvers.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://funkelab.github.io/ilpy/
  dev_url: https://github.com/funkelab/ilpy

extra:
  recipe-maintainers:
    - tlambert03
