{% set name = "ilpy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d8aa0938e8fead138b742c13ff2411fa9ccf406ed412b2fb511f8a8a3d37dc05

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - pyscipopt

test:
  imports:
    - ilpy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert version('ilpy') == '{{ version }}'"

about:
  home: https://github.com/funkelab/ilpy
  summary: 'Unified API for ILP solvers.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://funkelab.github.io/ilpy/
  dev_url: https://github.com/funkelab/ilpy

extra:
  recipe-maintainers:
    - tlambert03
